import type { Metadata } from "next";
import { LegalPage } from "@/components/marketing/LegalPage";
import { getSessionUser } from "@/lib/auth/session";
import { BUSINESS, legalEntityLine } from "@/lib/business";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How Gen Money collects, uses and protects your personal information.",
};

export default async function PrivacyPage() {
  const user = await getSessionUser().catch(() => null);

  return (
    <LegalPage
      title="Privacy Policy"
      updated={BUSINESS.legalUpdated}
      signedIn={Boolean(user)}
    >
      <p>
        This Privacy Policy explains how {legalEntityLine()} handles personal
        information for {BUSINESS.appName}. We aim to manage personal
        information consistently with Australian privacy requirements that apply
        to us, including the Australian Privacy Principles where applicable.
      </p>

      <h2>1. Information we collect</h2>
      <ul>
        <li>
          <strong>Account details:</strong> your name, email address, a salted
          cryptographic hash of your password, and optionally your state or
          territory.
        </li>
        <li>
          <strong>Financial records you enter or import:</strong> account names
          and types, opening balances, transactions, categories, budgets,
          savings goals and recurring bills. On the Professional plan this may
          include business/personal tagging and GST amounts.
        </li>
        <li>
          <strong>Subscription information received from Stripe:</strong> billing
          email, Stripe customer and subscription identifiers, subscription
          status, plan, billing interval and payment outcome.
        </li>
        <li>
          <strong>Support messages</strong> and contact information you choose to
          provide.
        </li>
        <li>
          <strong>Account emails</strong> we send you, such as password reset
          links. These are delivered through our email provider.
        </li>
        <li>
          <strong>Technical information</strong> generated by hosting and
          security systems, which may include IP address, browser and device
          information, timestamps and request logs.
        </li>
      </ul>

      <h2>2. What we do not collect</h2>
      <p>
        We do not ask for or store your internet banking credentials.{" "}
        {BUSINESS.appName} does not connect to your bank, screen-scrape your
        accounts, or initiate payments on your behalf. Transactions arrive only
        because you entered them or uploaded a statement you exported yourself.
        We do not collect your location.
      </p>

      <h2>3. Payment information</h2>
      <p>
        Full payment-card details are entered into Stripe-hosted payment pages
        and are not stored in the {BUSINESS.appName} database. Stripe processes
        those details under its own privacy and security obligations.
      </p>

      <h2>4. Why we use information</h2>
      <p>
        We use personal information to provide the service and show you your own
        records, operate subscriptions and entitlements, process support
        requests, prevent misuse, secure the service, maintain records, improve
        reliability and comply with legal obligations.
      </p>
      <p>
        We do not sell your personal information, and we do not use your
        financial records for advertising or profiling.
      </p>

      <h2>5. Who information may be disclosed to</h2>
      <p>
        We use service providers that process information on our behalf:
      </p>
      <ul>
        <li><strong>Stripe</strong> — subscription payments and billing.</li>
        <li><strong>Cloudflare</strong> — application hosting and network security.</li>
        <li><strong>Neon</strong> — the encrypted Postgres database that stores your records.</li>
        <li><strong>Resend</strong> — delivery of account emails such as password resets.</li>
      </ul>
      <p>
        We may also disclose information where required by law or reasonably
        necessary to protect legal rights, users or the service.
      </p>

      <h2>6. Overseas processing</h2>
      <p>
        Some service providers operate internationally. Personal information may
        therefore be processed or stored outside Australia, including in the
        United States and other locations used by those providers. We take
        reasonable steps to ensure overseas recipients handle your information
        consistently with the Australian Privacy Principles, and we will review
        provider locations and privacy arrangements as the service changes.
      </p>

      <h2>7. Direct marketing</h2>
      <p>
        We will not treat a purchase alone as consent for unrelated marketing
        messages. If we send commercial electronic messages, we will use consent
        where required, identify the sender and provide a functional way to
        unsubscribe.
      </p>

      <h2>8. Security</h2>
      <ul>
        <li>All traffic is served over HTTPS.</li>
        <li>
          Passwords are stored as salted PBKDF2-SHA256 hashes at a high iteration
          count, never in plain text or in a reversible form.
        </li>
        <li>
          Session tokens are stored as hashes, so a copy of the database cannot
          be used to sign in as you.
        </li>
        <li>Every database query is bounded to the signed-in account.</li>
        <li>Stripe webhooks are signature-verified before being processed.</li>
        <li>
          Password reset links are stored only as hashes, expire after one hour,
          work once, and sign out all existing sessions when used.
        </li>
        <li>Full card numbers are never stored.</li>
      </ul>
      <p>
        No online system can guarantee absolute security. We maintain a
        data-breach response process and will make notifications required by
        applicable law, including under the Notifiable Data Breaches scheme.
      </p>

      <h2>9. Retention</h2>
      <p>
        We keep information only for as long as reasonably needed for the
        purposes described above, to provide the service, resolve disputes, meet
        legal and accounting obligations and maintain security records. Payment
        and transaction records may need to be kept even after an account is
        deleted.
      </p>

      <h2>10. Access, correction and deletion</h2>
      <p>
        You can view and correct your records in the app at any time, and export
        them to CSV on a paid plan. You may ask what personal information we hold
        about you, request correction, or request deletion of your account by
        emailing{" "}
        <a
          href={`mailto:${BUSINESS.privacyEmail}`}
          className="font-semibold text-brand-600 hover:underline"
        >
          {BUSINESS.privacyEmail}
        </a>
        . We may need to verify your identity before releasing or changing
        information.
      </p>

      <h2>11. Privacy complaints</h2>
      <p>
        Send privacy concerns to{" "}
        <a
          href={`mailto:${BUSINESS.privacyEmail}`}
          className="font-semibold text-brand-600 hover:underline"
        >
          {BUSINESS.privacyEmail}
        </a>{" "}
        or {BUSINESS.postalAddress}. We will investigate and respond within a
        reasonable time. If an Australian privacy regulator has jurisdiction and
        you remain dissatisfied, you may also have a right to raise the matter
        with that regulator — in Australia, the Office of the Australian
        Information Commissioner at oaic.gov.au.
      </p>

      <h2>12. Cookies</h2>
      <p>
        {BUSINESS.appName} sets one essential cookie to keep you signed in. It is
        HttpOnly, restricted to this site, and is not used for advertising or
        cross-site tracking.
      </p>

      <h2>13. Children</h2>
      <p>{BUSINESS.appName} is not intended for people under 18.</p>

      <h2>14. Changes to this policy</h2>
      <p>
        We will update this policy when our information practices materially
        change and will update the date shown above. New data collection will not
        be hidden behind unrelated wording.
      </p>
    </LegalPage>
  );
}
